services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_healthy

  php:
    image: thecodingmachine/php:8.5-v5-fpm
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    env_file:
      - ./env.local
    environment:
      PHP_EXTENSION_INTL: "1"
      PHP_EXTENSION_PDO_PGSQL: "1"
      PHP_EXTENSION_PGSQL: "1"
      PHP_EXTENSION_ZIP: "1"
      PHP_EXTENSION_OPCACHE: "1"

      TEMPLATE_PHP_INI: production
      PHP_INI_MEMORY_LIMIT: 512M
      PHP_INI_DISPLAY_ERRORS: "1"
      PHP_INI_ERROR_REPORTING: E_ALL
      PHP_INI_DATE__TIMEZONE: Europe/Prague
      PHP_INI_OPCACHE__ENABLE: "1"
      PHP_INI_OPCACHE__ENABLE_CLI: "1"

    healthcheck:
      test: php -v || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  pg_data: