services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_healthy
    healthcheck:
      test: wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1
      interval: 10s
      timeout: 3s
      retries: 10

  php:
    image: thecodingmachine/php:8.5-v5-fpm
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./app/env.local
    environment:
      PHP_EXTENSION_INTL: "1"
      PHP_EXTENSION_PDO_PGSQL: "1"
      PHP_EXTENSION_PGSQL: "1"
      PHP_EXTENSION_ZIP: "1"
      PHP_EXTENSION_OPCACHE: "1"
      PHP_EXTENSION_XDEBUG: "1"

      TEMPLATE_PHP_INI: development
      PHP_INI_MEMORY_LIMIT: 512M
      PHP_INI_DISPLAY_ERRORS: "1"
      PHP_INI_ERROR_REPORTING: E_ALL
      PHP_INI_DATE__TIMEZONE: Europe/Prague
      PHP_INI_OPCACHE__ENABLE: "1"
      PHP_INI_OPCACHE__ENABLE_CLI: "1"
    healthcheck:
      test: php -r "echo 'ok';" >/dev/null 2>&1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U app -d app -h localhost
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 10

  composer:
    image: composer:2
    working_dir: /app
    volumes:
      - ./app:/app

volumes:
  pg_data: