# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # Bind interface to implementation
    App\Domain\User\UserRepository: '@App\Infrastructure\Persistence\InMemoryUserRepository'

    # HTTP Client service (Symfony automatically provides this)
    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    # HTTP Client for external services
    App\Infrastructure\Http\PlayersServiceClient:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%players_service.url%'
            $timeout: '%players_service.timeout%'

    App\Infrastructure\Http\WalletsServiceClient:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%wallets_service.url%'
            $timeout: '%wallets_service.timeout%'

    App\Infrastructure\Http\WithdrawalsServiceClient:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%withdrawals_service.url%'
            $timeout: '%withdrawals_service.timeout%'

    App\Infrastructure\Http\ReportsServiceClient:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%reports_service.url%'
            $timeout: '%reports_service.timeout%'

    App\Infrastructure\Http\ReferenceServiceClient:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%reference_service.url%'
            $timeout: '%reference_service.timeout%'

    App\Infrastructure\Http\SlotegratorServiceClient:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%slotegrator_service.url%'
            $timeout: '%slotegrator_service.timeout%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
